[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "amica-benchmark"
version = "0.1.0"
description = "Benchmark AMICA-Python vs Fortran AMICA"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "amica-python @ git+file:///Users/scotterik/devel/projects/amica-python/amica-python",
    "matplotlib",
    "mne",
    "numpy>=2",
    "pandas",
    "pooch>=1.8.2",
    "scipy",
    "tabulate",
    "torch",
]

[tool.setuptools]
py-modules = []
